/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Nikx
 */
public class pnl_admin extends javax.swing.JPanel {
private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    /**
     * Creates new form pnl_home
     */
    public pnl_admin() {
        initComponents();
        datatable();
    }
    
    protected void aktif(){
        pass.setEnabled(true);
        user.setEnabled(true);
        name.setEnabled(true);
        ket.setEnabled(true);
    }
    
    protected void kosong(){
        pass.setText("");
        user.setText("");
        name.setText("");
        ket.setText("");
    }
    
    public void datatable(){
        Object[] Baris ={"ID","Nama Admin","Username","Password","Keterangan"};
        tabmode = new DefaultTableModel(null, Baris);
        tabel_a.setModel(tabmode);
        String sql = "select * from admin ORDER BY id ASC";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){                
                String a = hasil.getString("id");
                String b = hasil.getString("nama");
                String c = hasil.getString("username");
                String d = hasil.getString("password");
                String e = hasil.getString("level");
                
            
                String[] data={a,b,c,d,e};
                tabmode.addRow(data);
            }
        } catch (Exception e){}
    }
    
    protected void cari(){
        Object[] Baris ={"ID","Nama Admin","Username","Password","Keterangan"};
        tabmode = new DefaultTableModel(null, Baris);
        tabel_a.setModel(tabmode);
        try {
        String sql = "select * from admin"
                + " WHERE nama LIKE '%" + carikk.getText() + "%' OR nama LIKE '" + carikk.getText() + "%' OR nama LIKE '%" + carikk.getText() + "'"
                + " ORDER BY id ASC";
            PreparedStatement pst = conn.prepareStatement(sql);
//            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = pst.executeQuery(sql);
            while(hasil.next()){
                String a = hasil.getString("id");
                String b = hasil.getString("nama");
                String c = hasil.getString("username");
                String d = hasil.getString("password");
                String e = hasil.getString("level");
            
                String[] data={a,b,c,d,e};
                tabmode.addRow(data);
            }
        } catch (Exception e){
        JOptionPane.showMessageDialog(null,e);}
    }
    
    public void erasetable(){
    if (tabmode.getRowCount() > 0) {
    for (int i = tabmode.getRowCount() - 1; i > -1; i--) {
        tabmode.removeRow(i);
    }
}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_a = new javax.swing.JTable();
        rSButtonRiple1 = new rojeru_san.RSButtonRiple();
        rSButtonRiple2 = new rojeru_san.RSButtonRiple();
        rSButtonRiple3 = new rojeru_san.RSButtonRiple();
        user = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        carikk = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        name = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ket = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        pass = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1010, 533));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("DATA ADMIN");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, 50));

        tabel_a.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_a.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabel_aFocusGained(evt);
            }
        });
        tabel_a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_aMouseClicked(evt);
            }
        });
        tabel_a.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tabel_aPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_a);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 220, 820, 180));

        rSButtonRiple1.setBackground(new java.awt.Color(227, 227, 227));
        rSButtonRiple1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rSButtonRiple1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_plus_filled_20px.png"))); // NOI18N
        rSButtonRiple1.setText("TAMBAH DATA");
        rSButtonRiple1.setColorHover(new java.awt.Color(0, 204, 153));
        rSButtonRiple1.setColorText(new java.awt.Color(0, 0, 0));
        rSButtonRiple1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple1ActionPerformed(evt);
            }
        });
        add(rSButtonRiple1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, -1, -1));

        rSButtonRiple2.setBackground(new java.awt.Color(227, 227, 227));
        rSButtonRiple2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rSButtonRiple2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_edit_file_filled_20px.png"))); // NOI18N
        rSButtonRiple2.setText("UBAH DATA");
        rSButtonRiple2.setColorHover(new java.awt.Color(0, 204, 153));
        rSButtonRiple2.setColorText(new java.awt.Color(0, 0, 0));
        rSButtonRiple2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple2ActionPerformed(evt);
            }
        });
        add(rSButtonRiple2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, -1, -1));

        rSButtonRiple3.setBackground(new java.awt.Color(227, 227, 227));
        rSButtonRiple3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rSButtonRiple3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_delete_filled_20px_1.png"))); // NOI18N
        rSButtonRiple3.setText("HAPUS DATA");
        rSButtonRiple3.setColorHover(new java.awt.Color(0, 204, 153));
        rSButtonRiple3.setColorText(new java.awt.Color(0, 0, 0));
        rSButtonRiple3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonRiple3ActionPerformed(evt);
            }
        });
        add(rSButtonRiple3, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, -1, -1));

        user.setPreferredSize(new java.awt.Dimension(0, 0));
        add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 150, 20));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 660, 10));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Mode Pencarian");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, -1, -1));

        jLabel4.setText("Nama");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        jLabel5.setText("Keterangan");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        carikk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carikkActionPerformed(evt);
            }
        });
        carikk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                carikkKeyReleased(evt);
            }
        });
        add(carikk, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, 150, -1));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 110, 30, 110));
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 130, -1));

        ket.setColumns(20);
        ket.setRows(5);
        jScrollPane2.setViewportView(ket);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 190, 50));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(792, 80, 30, 130));

        jLabel7.setText("Username");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));
        add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 150, -1));

        jLabel8.setText("Password");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jLabel9.setText("Nama Admin");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Masukkan Data");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));
        add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 0, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonRiple3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple3ActionPerformed
//         tabel_j.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
//         int[] selectedRows = tabel_j.getSelectedRows();
//        StringBuilder b = new StringBuilder();
//  b.append("delete from jabatan where ");
//  for (int i = 0; i < selectedRows.length; i++) {
//      int row = selectedRows[i]; 
//      String no = tabmode.getValueAt(row, 0).toString();
//      b.append("kd_jabatan='"+no+"'");
//      if (i < selectedRows.length - 1) {
//         b.append(" OR ");  //omit the last OR
//      } 
//  }
//  try {
//               PreparedStatement stat = conn.prepareStatement(b.toString());
//               stat.executeUpdate(b.toString());
//               JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
//               datatable();
//           }catch (SQLException e){
//               JOptionPane.showMessageDialog(null, "Data gagal dihapus"+e);
//           }



        int ok = JOptionPane.showConfirmDialog(null, "Yakin untuk di hapus ?","Konfirmasi Dialog", JOptionPane.YES_NO_OPTION);
       if (ok==0){
           String sql = "delete from admin where id ='"+id.getText()+"'";
           try {
               PreparedStatement stat = conn.prepareStatement(sql);
               stat.executeUpdate();
               JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
               datatable();
           }catch (SQLException e){
               JOptionPane.showMessageDialog(null, "Data gagal dihapus"+e);
           }
       }
    }//GEN-LAST:event_rSButtonRiple3ActionPerformed

    private void rSButtonRiple1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple1ActionPerformed
      String sql = "insert into admin (username,password,nama,level) values (?,?,?,?)";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, user.getText());
            stat.setString(2, pass.getText());
            stat.setString(3, name.getText());         
            stat.setString(4, ket.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            datatable();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+e);
        }
    }//GEN-LAST:event_rSButtonRiple1ActionPerformed

    private void tabel_aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_aMouseClicked
       int bar = tabel_a.getSelectedRow();
       String a = tabmode.getValueAt(bar, 0).toString();
       String b = tabmode.getValueAt(bar, 1).toString();
       String c = tabmode.getValueAt(bar, 2).toString();
       String d = tabmode.getValueAt(bar, 3).toString();
       String e = tabmode.getValueAt(bar, 4).toString();
       
       id.setText(a);
       name.setText(b);
       user.setText(c);
       pass.setText(d);
       ket.setText(e);
    }//GEN-LAST:event_tabel_aMouseClicked

    private void tabel_aFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabel_aFocusGained

    }//GEN-LAST:event_tabel_aFocusGained

    private void tabel_aPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tabel_aPropertyChange
       
    }//GEN-LAST:event_tabel_aPropertyChange

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        
    }//GEN-LAST:event_formMouseEntered

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        
    }//GEN-LAST:event_formPropertyChange

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
       
    }//GEN-LAST:event_formMouseMoved

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
       
    }//GEN-LAST:event_formFocusGained

    private void rSButtonRiple2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonRiple2ActionPerformed
       String sql = "update admin set username=?,password=?,nama=?,level=? where id=?";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, user.getText());
            stat.setString(2, pass.getText());
            stat.setString(3, name.getText());
            stat.setString(4, ket.getText());  
            stat.setString(5, id.getText());          
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            kosong();
            datatable();
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+e);
        }
    }//GEN-LAST:event_rSButtonRiple2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       datatable();
       kosong();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void carikkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carikkActionPerformed
       
    }//GEN-LAST:event_carikkActionPerformed

    private void carikkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carikkKeyReleased
        cari();
    }//GEN-LAST:event_carikkKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField carikk;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextArea ket;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pass;
    private rojeru_san.RSButtonRiple rSButtonRiple1;
    private rojeru_san.RSButtonRiple rSButtonRiple2;
    private rojeru_san.RSButtonRiple rSButtonRiple3;
    public javax.swing.JTable tabel_a;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
