/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package panel;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import javax.swing.JOptionPane;

/**
 *
 * @author Nikx
 */
public class pnl_home extends javax.swing.JPanel {
private Connection conn = new koneksi().connect();


    /**
     * Creates new form pnl_home
     */
    public pnl_home() {
        initComponents();
        pemasukan();
        pengeluaran();
        totalkas();
    }
    
    private void pemasukan(){
        try{
          String sql="select SUM(masuk) AS pemasukan from kas_masuk";
          PreparedStatement pst = conn.prepareStatement(sql);
          ResultSet rs=pst.executeQuery(sql);
          
          while(rs.next()){
          String pemasukans =rs.getString("pemasukan");
          if(pemasukans == null){pemasukans = "0";}
          temp_masuk.setText(pemasukans);
          }
          
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void pengeluaran(){
        try{
          String sql="select SUM(keluar) AS pengeluaran from kas_keluar";
          PreparedStatement pst = conn.prepareStatement(sql);
          ResultSet rs=pst.executeQuery(sql);
          
          while(rs.next()){
          String pengeluarans =rs.getString("pengeluaran");
          if(pengeluarans == null){pengeluarans = "0";}
          temp_keluar.setText(pengeluarans);
          }
          
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
        }
    }
    
    private void totalkas(){
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();
        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);
        
        double masuks,keluars,totals;
        masuks = Double.parseDouble(temp_masuk.getText());
        keluars = Double.parseDouble(temp_keluar.getText());
        totals = masuks-keluars;
        String masukk = String.valueOf(kursIndonesia.format(masuks));
        String keluarr = String.valueOf(kursIndonesia.format(keluars));
        String saldos = String.valueOf(kursIndonesia.format(totals));
        masuk.setText(String.valueOf(masukk));
        keluar.setText(String.valueOf(keluarr));
        saldo.setText(String.valueOf(saldos));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        keluar = new javax.swing.JLabel();
        saldo = new javax.swing.JLabel();
        masuk = new javax.swing.JLabel();
        temp_keluar = new javax.swing.JLabel();
        temp_masuk = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1010, 533));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LOGO.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 230, 200));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_money_100px.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Initiate_Money_Transfer_100px_1.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Request_Money_100px.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        keluar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        keluar.setText("Keluar");
        add(keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, 20));

        saldo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        saldo.setText("Saldo");
        add(saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, -1, -1));

        masuk.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        masuk.setText("Masuk");
        add(masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, -1, -1));

        temp_keluar.setText("jLabel5");
        add(temp_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 10, 0));

        temp_masuk.setText("jLabel5");
        add(temp_masuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 10, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Total Kas Masuk");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Total Saldo akhir");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Total Kas Keluar");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel keluar;
    private javax.swing.JLabel masuk;
    private javax.swing.JLabel saldo;
    private javax.swing.JLabel temp_keluar;
    private javax.swing.JLabel temp_masuk;
    // End of variables declaration//GEN-END:variables
}
